export const SET_EXERCISE_VISIBILTY = "SET_EXERCISE_VISIBILTY";
export const FILTER_EXERCISES = "FILTER_EXERCISES";
export const NAV_OPEN = "NAV_OPEN";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';